### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by MudassarMemon** [danielhlee4/TuneUp#84]
### Description

- The search functionality is intended to enable users to search for TuneUps and/or Users by first and last name, instruments and genres.

### Current Progress

- The search feature currently allows searching for TuneUps based on instruments and genres

### Tasks Required for Completion

- [x] Sort results by date
- [x] Frontend styling 

### Bonus implementation
- [ ] Error handling (no tuneups found message) (bonus)
- [ ] Update production readme
- [ ] Sort results by distance (bonus)
- [ ] Create frontend search result components with link to users profile (bonus)
- [ ] Dynamic dropdown while searching (bonus)
- [ ] Search by Users first name, last name or instruments (bonus)
- [ ]  Exclude inactive (closed/past) TuneUps from results  (bonus)
